return {
	["Speed"] = {
		Image = 114124336527832,
		MaxAmount = 3,
		Price = 250,
        Cooldown = 3,
		Name = "Speed",
        Description = "Speed boost for a short duration.",
    },
    ["Invisibility"] = {
        Image = 133355043444426,
        MaxAmount = 1,
        Price = 300,
        Cooldown = 5,
        Duration = 3,
        Name = "Invisibility",
        Description = "Become invisible for a short duration.",
    },
} 