return {
	["Dash"] = {
		Image = 16071029634,
		Stock = 30,
		Price = 250,
		Chance = 85,
        Cooldown = 3,
		Name = "Dash",
        Description = "Quickly dash forward a short distance.",
    },
    ["Invisibility"] = {
        Image = 93283105208820,
        Stock = 1,
        Price = 300,
        Chance = 20,
        Cooldown = 5,
        Duration = 3,
        Name = "Invisibility",
        Description = "Become invisible for a short duration.",
    },
    ["Double Jump"] = {
        Image = 90682070728446,
		Stock = 1,
		Price = 300,
		Chance = 50,
		Cooldown = 5,
		Name = "Double Jump",
        Description = "Jump again while in the air.",
    } 
} 