return {
	["Complete 5 Generators"] = {
		Type = "Survivor",
		Description = "Complete 5 generators in a single round",
		Goal = 5,
		Reward = 100,
		RewardType = "Cash",
	},
	["Survive 3 Rounds"] = {
		Type = "Survivor",
		Description = "Survive and escape 3 rounds",
		Goal = 3,
		Reward = 150,
		RewardType = "Cash",
	},
	["Escape Through Gate"] = {
		Type = "Survivor",
		Description = "Successfully escape through the gate",
		Goal = 1,
		Reward = 100,
		RewardType = "Cash",
	},
	["Eliminate 5 Survivors"] = {
		Type = "Killer",
		Description = "Eliminate 5 survivors as the killer",
		Goal = 5,
		Reward = 300,
		RewardType = "Cash",
	},
	["Win 3 Rounds as Killer"] = {
		Type = "Killer",
		Description = "Win 3 Rounds as Killer",
		Goal = 3,
		Reward = 250,
		RewardType = "Cash",
	},
	["Use 10 Perks"] = {
		Type = "Both",
		Description = "Use 10 perks in total",
		Goal = 10,
		Reward = 200,
		RewardType = "Cash",
	},
}