return {
    Coins = 10000,
    Shop = {},
    RestockTimer = 0,
    MaxKillerPerkMana = 3,
    MaxSurvivorPerkMana = 3,
    OwnedKillerPerks = {},
    OwnedSurvivorPerks = {},
    Perks = {
        Slot1 = {
            Name = "",
            Quantity = 0
        },
        Slot2 = {
            Name = "",
            Quantity = 0
        },
        Slot3 = {
            Name = "",
            Quantity = 0
        }
    },

    SurvivorPerks = {
        Slot1 = {
            Name = "",
            Quantity = 0
        },
        Slot2 = {
            Name = "",
            Quantity = 0
        },
        Slot3 = {
            Name = "",
            Quantity = 0
        }
    },

    ActiveQuests = {},
    QuestProgress = {},
    LastQuestResetTime = 0,

}
