return {
    Cash = 10000,
    Shop = {},
    RestockTimer = 0,
    Perks = {
        Slot1 = {
            Name = "",
            Quantity = 0
        },
        Slot2 = {
            Name = "",
            Quantity = 0
        },
        Slot3 = {
            Name = "",
            Quantity = 0
        }
    },

    Abilities = {
        Slot1 = {
            Name = "",
            Quantity = 0
        },
        Slot2 = {
            Name = "",
            Quantity = 0
        },
        Slot3 = {
            Name = "",
            Quantity = 0
        }
    },

}
